"""Add failed_logins field

Revision ID: 347b054cfdb
Revises: fe0b9b9da9
Create Date: 2015-03-31 10:13:51.306896

"""

# revision identifiers, used by Alembic.
revision = '347b054cfdb'
down_revision = 'fe0b9b9da9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('failed_logins', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'failed_logins')
    ### end Alembic commands ###
