"""Initial migration

Revision ID: fe0b9b9da9
Revises: None
Create Date: 2015-03-31 10:12:38.822255

"""

# revision identifiers, used by Alembic.
revision = 'fe0b9b9da9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###
